=encoding utf-8

=head1 NAME

Image::PNM - Interface for PNM format image file

=head1 SYNOPSIS

    use Image::PNM;
    my $img = Image::PNM->new;
    $img->load($filepath);
    $img->width; $img->height;
    $img->getpixel(1, 2);
    $arr_ref = $img->bitmap;
    
    # or
    use Image::PNM qw/load_pnm/;
    my $bitmap = load_pnm($filepath);   # exported

=head1 DESCRIPTION

Image::PNM is a light weight image interface for PNM formatted image file,

which is ppm, pgm, pbm;


It can only load image or save image.

But lighter than other Image libraries.

saving method has not been implemented yet.

you can only access on load or load_pnm methods now.


=head1 LICENSE

Copyright (C) Aiga Suzuki.

This software is released under MIT License.

=head1 AUTHOR

Aiga Suzuki

=cut
